version: '3.7'

## docker-compose for running mongodb in container
## sudo docker-compose -f "dc-MongoDB.yml" up  -d
## sudo docker-compose -f "dc-MongoDB.yml" down -v
services:
  mongo:
    image: mongo
    container_name: ctn-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - mycommunity-network
  mongo-express:
    image: mongo-express
    container_name: ctn-mongo-express
    restart: always
    ports:
      - 8100:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
    networks:
      - mycommunity-network
networks:
  mycommunity-network:
    driver: bridge
